name: SchoolEye Deploy
on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Restore
        run: dotnet restore BlazorGlobalizationDashboard.sln
      - name: Build
        run: dotnet build BlazorGlobalizationDashboard.sln --configuration Release --no-restore

      - name: Stop App Pools
        shell: powershell
        run: |
          Import-Module WebAdministration
          Stop-WebAppPool -Name "Newpool"
        

      - name: Publish API
        run: |
          dotnet publish BlazorGlobalizationDashboard/BlazorGlobalizationDashboard.csproj `
          -c Release `
          -o D:\PublishNew

    

      - name: Start App Pools
        shell: powershell
        run: |
          Import-Module WebAdministration
          Start-WebAppPool -Name "Newpool"
       
